#!/usr/bin/env bash

export DISPLAY=:1

if pgrep Xtigervnc > /dev/null; then
    echo "[!] VNC already running"
    exit 1
fi

echo "[*] Starting VNC server..."

dbus-launch --exit-with-session \
vncserver :1 -geometry 1280x720 -depth 24 -localhost no

echo "[✓] VNC started on :1"